### ISSUE TITLE
Create annotate file from Hi-C data

### ISSUE THREAD

**Issue by kvshams** [thewonlab/H-MAGMA#5]
Thank you for the great package. It would be great to provide the commands/code that you used to create .annotate of Hi-C file from magma and that would allow to generalize this method for other diseases.
Thanks,
Shams

**Comment by jamesdalg** [comment]
I agree. It's really hard to make use of this tool without an ability to work on other tissues. The paper doesn't go into enough detail to replicate the work (specifically the initial preprocessing with fitdistrplus), so it's hard to know how to generate the files. It would be nice if the package had a complete pipeline to recreate what you did so that others can use the method. I did this for my package.
Please provide necessary code to use H-MAGMA on other, more esoteric datasets.

**Comment by BioCXH** [comment]
you can try Activity-by-Contact (ABC) model
https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction and https://github.com/EngreitzLab/ABC-GWAS-Paper
ABC provide enough details for each step.

**Comment by seynancy** [comment]
Hi all, thank you for using H-MAGMA and apologies for the delayed response. We are working to establish a protocol on how to create the .annotate file used to run H-MAGMA. We are also working to expand H-MAGMA by generating annotation files for several cell types other than brain tissues. While the second portion may take some time, we hope that the protocol, which should be available in a couple of months will allow others to generate their own annotation file in the mean time. Thanks again for using the program and we welcome all feedback on how to improve the tool!

**Comment by kvshams** [comment]
@seynancy any update on the protocol? 
thanks,
Shams

**Comment by seynancy** [comment]
Hi Shams,

Apologies about the wait. The protocol is now available! Due to the size of the files, we are unable to upload it directly to GitHub but you can obtain all necessary files by following this link https://zenodo.org/record/5503877#.YT9ZqZ5Kg1I

**Comment by hyejungwon** [comment]
@kvshams 
The code for generating H-MAGMA annotation file is also under `Codes/H-MAGMA_annotation_generation.rmd`. Please check out and let use know if you have any question!
